server:
  port: 9192

spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/pushman_db
    driver-classname: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    servlet:
      multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
